import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {children}
        <footer className="fixed bottom-0 left-0 right-0">
          <div className="flex justify-center items-center h-10 text-gray-400 bg-white">
            <a
              href="https://github.com/tsuki-lab/next-isr-chat"
              target="_blank"
              rel="noopener noreferrer"
              className="flex justify-center items-center"
            >
              GitHub Repository
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
